# Generated by Django 4.2 on 2023-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product_image',
            name='image',
            field=models.ImageField(null=True, upload_to='media/product_images'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/banner_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to='media/product_images'),
        ),
    ]
