# Generated by Django 4.2 on 2023-04-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
